server:
  port: 8070

spring:
  jpa:
    show-sql: true
    open-in-view: true


    properties:
      hibernate:
        jdbc:
          batch_size: 500
  datasource:
    username: root
    password: 654123
    url: jdbc:mysql://localhost:3306/PigPrice?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
